# Generated by Django 5.1.4 on 2024-12-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lessonplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lsid', models.CharField(max_length=20)),
                ('descp', models.CharField(max_length=255)),
                ('cosn', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'lessonplan',
            },
        ),
    ]
